### ISSUE TITLE
Info - Document Side Panel

### ISSUE THREAD

**Issue by rickatech** [rickatech/backstage#14]
Documents in ProLoop may have additional 'meta' information associated with them that is not contained in the actual document.

In the MS Office plug-in, the ribbon side panel has an Info section.  When a document is opened, clicking the info side panel will display two editable fields

- summary
- author

clicking either field allow it to be edited (this can be a popup).

with two buttons
[ reload ] [ save ]

Storage (now)
  - a text file, with filename exactly the same as the open file, but with ..._info.txt file ending.  The file will be a JSON text for the summary and authors values.

Storage (future)
  - API read and save/update will be provided

![gh_014a](https://user-images.githubusercontent.com/11014263/32589874-f2c664b8-c4cb-11e7-82f4-ca8ef3f05340.png)
![gh_014b](https://user-images.githubusercontent.com/11014263/32589875-f2ddbe60-c4cb-11e7-9be1-711c4a8f7ed7.png)

**Comment by shahshyam** [comment]
it has implemented .
