### ISSUE TITLE
backstage icon graphic + ProLoop

### ISSUE THREAD

**Issue by rickatech** [rickatech/backstage#2]
Please use attached icon for backstage graphic, then present only the text ProLoop to the right

![balance_justice_blue](https://cloud.githubusercontent.com/assets/11014263/22815178/7587d59c-ef0e-11e6-9188-3bf891ba6e73.png)

**Comment by sdn-dev** [comment]
Changed the icon to provided Logo image.
Text changed from "Sabre.io WebDAV" to "ProLoop" in v2.1.
