### ISSUE TITLE
Plug-in will not show - workaround needed

### ISSUE THREAD

**Issue by rickatech** [rickatech/backstage#28]
![image](https://user-images.githubusercontent.com/11014263/39909688-bc1c82b8-54a8-11e8-9406-c5eaf5ca6cb3.png)

This seems to be due to an update Microsoft made that breaks legacy MS Office plugins.
https://www.add-in-express.com/forum/read.php?FID=5&TID=14930

**Comment by rickatech** [comment]
From QA group:
Using workaround for compatibility currently works for the application, App works relatively fine with compatibility option enabled.

**Comment by rickatech** [comment]
There is a fixed plug-in with a fix ... testing in progress.

**Comment by shahshyam** [comment]
It is fixed with addin-Express 9.xx
