### ISSUE TITLE
Plug-in Guard

### ISSUE THREAD

**Issue by rickatech** [rickatech/backstage#4]
[ placeholder from previous conversation ]

Developer mentioned complex MS Office plugin installers can sometimes walk on other plugins.  There is a special guard mechanism to protect this plugin so that it is less vulnerable to being corrupted by other installers.

**Comment by sdn-dev** [comment]
The Add-in guard is a COM Shim.

**Comment by sdn-dev** [comment]
I've migrated the code starting v4.0 to Add-in Express. We have the guard mechanism in place for our Add-in.

**Comment by rickatech** [comment]
With version v4.0, "Add-in Express for Microsoft Office and .net, Professional" is being used which also addresses this.
