### ISSUE TITLE
Post install, reconfigure file mount path

### ISSUE THREAD

**Issue by rickatech** [rickatech/backstage#5]
Currently, plug-in is hard coded to use the http://newui.proloop.com/dav file mount path.  Need a way to allow developers, testers, and production to use the same plugin, but customize the file mount path.

Look into feasibility of making a regedit or other run time configuration option to adjust this to an alternate path.

Examples of alternate paths:
  https://dav.proloop.com/
  http://sj01.proolop.com/dav
  http://rk01.proloop.com/dav

**Comment by sdn-dev** [comment]
It's possible. We can accomplish by setting the path for the folder:

1. in a settings XML file
2. in a registry key

Add-in will read this value while it is loading and mount the drive to this folder. I'll include this in P3.

**Comment by proloopdev** [comment]
Either could work, is there already an XML that could add this setting to?  If not regedit approach is okay too.

**Comment by sdn-dev** [comment]
- [x] I chose the registry (currently logged on user's registry portion/HKCU) for saving the settings, Please download the **v3.0** build of the program to review. 

**Steps:**
- Download the .reg file (from Dropbox **V3** folder)
- Change any settings (URL, Username, or Password)
- Double click on it to import the necessary registry keys before launching MS Word.

**Comment by rickatech** [comment]
This seems to work as you describe.

However, I'm going to adjust requirements a little bit.

* Server path is always pulled from user's registry portion/HKCU
    e.g. "URL"="http://newui.proloop.com/dav/", with a prompt/error if the key is not found
* If either Username or Password is missing from registry portion/HKCU, fallback to v2.1 basic mount (which I think assumes OS handles username/password prompting upon volume mount)

With the above it will be easier to debug/isolate any issue with Win7 vs WIn10 mounting volume issues.  Currently I have to uninstall the plugin v2.1 <-> v3 if I disable WebDAV authentication for volume mounting debugging.  Does changing user's registry portion/HKCU require reboot for plugin to notice?

**Comment by sdn-dev** [comment]
* Server path is always pulled from user's registry portion/HKCU
-- Correct.
* If either Username or Password is missing from registry portion/HKCU, fallback to v2.1 basic mount (which I think assumes OS handles username/password prompting upon volume mount)
-- Saving password in registry is not a best practice. We'll have to store the credentials in a secure per-Windows user store (isolated storage) and use this for authenticating with the WebDAV server. I was saving the username and password in the registry as a stop-gap workaround.

**Comment by rickatech** [comment]
Thanks for council on best practice for storing username / password.

For now it is okay to use registry as its easier to see/debug.  But, yes it will need to move at some point.

**Comment by sdn-dev** [comment]
Sounds good. We can use registry for storing all 3 parameters for now..

Also, when username and/password is missing from registry, the drive mapping Windows API call will fail. OS will not interfere at all. We'll have to provide a prompt for credentials, save it in registry and then pass it to the API call to map the drive successfully.

**Comment by rickatech** [comment]
Hello, I created a github WIki page at
https://github.com/rickatech/backstage/wiki/User-Guide

If we can document how an 'advanced' end user can change their ProLoop path URL and reset their username on the WIki, I think this ticket can be closed.
