### ISSUE TITLE
UI / check in / check out

### ISSUE THREAD

**Issue by rickatech** [rickatech/backstage#6]
Eventually there needs to be a popup when attempting to Save File, Save As File.

For now can just present a popup form, upon submit not bother calling any API's, but allow users to fill it out/see it.  Later (separate issue) we can add API requirements for what to do with form field values / and any validation / real-time REST calls.

From sponsor's requirements

* The new UI needs to incorporate the check in / check out that already exists in the original system. It’s important to be able to type in the client name OR # in the “Client” field, and likewise the matter description OR # in the “Matter” field.
“Name” of course refers to the document name.

![check-in](https://cloud.githubusercontent.com/assets/11014263/23246075/ed7254ec-f945-11e6-9b49-b2bfbf31a99d.jpg)

![ms_word_save_imanage](https://cloud.githubusercontent.com/assets/11014263/24038139/655b3cd4-0abd-11e7-8ea2-b89e4bb178f2.png)

**Comment by sdn-dev** [comment]
Check-in/out, Versioning are features of WebDAV. However, when we map a drive (the way we'd been doing), it will only enable us to read/save a file just like a local hard disk drive. It doesn't provide any WebDAV facilities (check in/out, etc). So, we'll have to abandon the drive mapping and make calls using WebDAV client API.

**Comment by rickatech** [comment]
Thanks for the better description of check-in/checkout.  If that's the case, we can hold off off check-out for a bit.

Phase 1 - simple popup with dummy forms, submit doesn't do anything special, proceeds to save file
Phase 2 - a REST API is called upon submit, form data is sent to server API for later processing
Phase 3 - switch in WebDAV API for check-out/check-in functions

**Comment by sdn-dev** [comment]
Thanks for the details. I'm fine with the phases.

**Comment by rickatech** [comment]
Phase 1 - Dummy Form, Mark 1

    Project OR Organization [ switch, default to Projects for now ]
    Projects                [ drop down of projects user is a member of ] (ghosted for Organization)
    Client                  [ drop down of clients user has access to ]   (ghosted for Project)
    Matter                  [ drop down of matters user has access to ]   (ghosted for Project)
    File browser
    File path (read only FYI)

![github_oc_6_0](https://cloud.githubusercontent.com/assets/11014263/24037953/ac24b682-0abc-11e7-9355-e02877d3fa2b.jpg)

**Comment by sdn-dev** [comment]
In v4.0, form fields have been integrated into Word 2016 Backstage Menu -> Open/Save As -> ProLoop.
Please download v4.0 of Add-in installer from https://www.dropbox.com/sh/7wf71w4ts1ifr6f/AACIMHRuzyDq2GTLFJLvvAJsa?dl=0

**Comment by rickatech** [comment]
Windows developer provided v4.0 of MS Office plug-in with a dummy form that asks for client and matter upon save.

This now uses the advanced commercial "Add-in Express for Microsoft Office and .net, Professional" for better security and customization.

Phase 1 - Dummy Form, Mark 2

![win_saveas_v40a](https://cloud.githubusercontent.com/assets/11014263/24185872/a9962980-0e92-11e7-8ee5-309954e08c93.jpg)

**Comment by rickatech** [comment]
Closing this as M3 complete.
